apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a4odft85z-python 
  janus-idp.io/tekton: a4odft85z-python
  backstage.io/kubernetes-id: a4odft85z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a4odft85z-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml